### ISSUE TITLE
Zaimplementować POSIXowy semafor jako klasę dziedziczącą z abstrakcyjnej klasy semafora (inny task)

### ISSUE THREAD

**Issue by mrcn4** [mrcn4/UXP1A-Linda#12]

**Comment by MGJanicki** [comment]
Potrzebujemy tylko POSIXoweg semafora czy tego z SYSV też?

**Comment by nuivall** [comment]
A czy nie brakuje przypadkiem destruktorow w  tych semaforach? (w trym virtualnego)

**Comment by mrcn4** [comment]
Poprawione.

**Comment by nuivall** [comment]
chyba się rozjedzie przy kopiowaniu. Albo zaimplementować albo zablokować.

**Comment by mrcn4** [comment]
w projekcie nie ma kopiowania semaforów(tylko wskaźników na nie). Czyli działa, ale w ogólności do zablokowania, potwierdzam.
