### ISSUE TITLE
Kod klienta: input

### ISSUE THREAD

**Issue by mrcn4** [mrcn4/UXP1A-Linda#13]

**Comment by nuivall** [comment]
ten readd() w kliencie to specjalnie 2x d ? A tak poza tym to co pozostaje oczyscic kod i napisac klienta testowego (symulacja ze sprawdzaniem poprawnosci) i ewentualnie jakiegos SampleClient. Czy czegos jeszcze brak?

**Comment by mrcn4** [comment]
Tymczasowe rozwiązanie, miałem konflikty w nazwach z biblioteką C. Jakiś
klient/ serwer korzystający z nagłówków i biblioteki do napisania-
skompilowac do .a albo .so (obecnie main serwera uruchamia klientów z
parametru cmdline, klienci testują prostą funkcjonalność). Kod nie jest
optymalny, w szczególności powtarzanie query gdy nie było spełnione za
pierwszym razem ma potencjał do poprawy. Doxygen. Sytuacje typu "serwer
ginie", "klient ginie" w różnych momentach (kill). Semafory są POSIX, więc
pewnie nie każda sytuacja zabijania jest ok(brak UNDO).
11 cze 2013 02:13, "Marcin M" notifications@github.com napisał(a):

**Comment by nuivall** [comment]
Czesciowym (ale byc moze wystarczajacym) rozwiazaniem braku sem_undo moze byc wolanie destruktorow w obsludze sygnalow.

Problemem jest chyba tylko SIGKILL, nie wiem dokladnie w jakich sytuacjach system moze go wyslac, ale jezeli user zrobi kill -SIGKILL to jakby sam jest sobie winien.

handle_read, handle_input to mozna chyba jakos polaczyc? (bo sa prawie identyczne, w _read jest obsluga bledow lepsza)

Zabijanie serwera i clienta to bedzie ciezko przetestowac (moze jakas funkcja debug_random_kill w niektorych miejscach kodu klienta/serwera?)

**Comment by nuivall** [comment]
Dodalem seachParsedClientRequests(), nie wiem czy to sie pojawilo? Bo cos dziwnie mi dziala ten github

**Comment by nuivall** [comment]
Bo ten commit (d289492aba6aae00146047ac412d392bfaeff2fb) nie pokazuje sie w historii, nie wiem gdzie on sie podzial.

**Comment by mrcn4** [comment]
readd fixed -> read. Połączone handle_read i handle_input. Zabijanie klienta wykrywane przez błąd na pipe.
