### ISSUE TITLE
ParsedRequest co to?

### ISSUE THREAD

**Issue by nuivall** [mrcn4/UXP1A-Linda#16]
Chyba sie pogubilem, do czego sluzy ta klasa? (i ktorego issue dotyczy)

**Comment by MGJanicki** [comment]
W sumie to jest kosmetyka.
To jest strukturka, w której jest trzymane zapytanie po stronie serwera. Potrzebujemy jej, żeby za każdym razem nie parsować zapytania, tylko zrobić to raz, a potem wywoływać. W sumie dotyczy tego issue, które zamknąłeś wczoraj wieczorem.

**Comment by nuivall** [comment]
Spojrz na klase TupleQuery z TupleDatabase (moze nalezy wydzielic do osobnego pliku, poczatkowo uznalem ze jest scisle powiazana z baza danych). 

Marcin S dokonal drobnej modyfikacji TupleDatabase read/input/output i mozna teraz to samo zapytanie wykonywac wiele razy (chociaz w sumie nie wiem po co taka opcja - czy jest taki machanizm w dokumentacj?)

**Comment by MGJanicki** [comment]
Commit jest mój, zapomniałem ustawić username w configu gita na Linuxie. 

Odpowiadając na Twoje pytanie - tak, przewidujemy taką możliwość, możliwe, że pominęliśmy to w dokumentacji, bo brakowało miejsca (trzeba było oddać dokumentację liczącą do 4 stron). Sytuacja, w której jest to wykorzystywane rysuje się następująco:
1. Klient wysyła żądanie input(pattern)
2. Serwer nie znajduje krotki pasującej do wzorca
3. Żądanie zostaje zapisane i będzie ponownie sprawdzone w momencie, w którym któryś z klientów wyślę żądanie output dodając jakąś krotkę do bazy.
W związku z tym musimy mieć jakąś strukturę, która przechowuje typ zapytania, jego tag oraz samo zapytanie.

**Comment by nuivall** [comment]
Ok rozumiem. Trzeba dodac taski z obsluga protokolu. Ja tak umiarkowanie wiem co trzeba tam zrobic, a co jest robione w obrebie TupleClient/Server. 

To deserializeReq trzeba zmienic nazwe na extractRequest, albo deserializeRequest i zamknac to w jakies klasie obslugi protokolu. A najlepiej to zamiast Request uzywac ClientRequest bo poczatkowo myslalem ze chodzi w tym o zapytanie do bazy danych (jako query).
