### ISSUE TITLE
Serializacja i deserializacja krotki

### ISSUE THREAD

**Issue by mrcn4** [mrcn4/UXP1A-Linda#2]

**Comment by MGJanicki** [comment]
W dokumentacji brakuje wzorca zserializowanej krotki. Są jakieś pomysły czy mam sam coś wykombinować?

**Comment by mrcn4** [comment]
Chodzi właśnie o wymyślenie. Jako wynik serializacji ma być ciąg bajtów, którzy można wrzucić w message przesyłany przez pipe. Jedynym ograniczeniem formatu jest możliwość deserializacji - ten moduł jest w dużej mierze niezależny od innych.

**Comment by MGJanicki** [comment]
Ok, ja myślałem o serializowaniu krotki do formatu: typ-wartość|typ-wartość|...|typ-wartość#. Zaraz to napiszę i zobaczę jak to będzie działać. Jest tylko jeden problem z tego typu serializacją - wykluczam możliwość występowania znaków "-", "|" i "#" z wartości stringów znajdujących się w TupleElement.

**Comment by mrcn4** [comment]
Lepiej zrób dla stringa długość stringa na początku i będzie spokój, reszta ma stałą długość to nie potrzebne separatory.

**Comment by nuivall** [comment]
Sugeruje cos ala json. Prosty format, szeroko uzywany, moze jest w necie jakas biblioteka wspomagajaca.

**Comment by MGJanicki** [comment]
Już zrobiłem serializację na zasadzie typ-wartość lub typ-długość_danych-wartość w wypadku stringa i jest to w postaci gotowej do wysłania pipem. Jak skończę deserializację to wrzucę całość razem z prostym testem.

**Comment by MGJanicki** [comment]
Według mnie to by było na tyle w temacie serializacji i deserializacji krotek. Wrzuciłem przykładowego maina opartego o maina Marcina M z pliku Tuple.hpp z prostymi testami dla tych funkcji. Jeżeli uznacie, że to co zrobiłem jest ok to można zamknąć to zadanie.

**Comment by nuivall** [comment]
troche trzeba poprawic, wiecej w commit-info. Raczej unikaj memcpy, format moze byc jakis prosty w stylu: 

I_222 F_22.12 S_"ala ma zawiera cudzyslow \" escaped \" kota" 

takie cos nie jest trudno sparsowac, a za to latwo czytac (debugujac), zauwaz ze prefix typu jest stalej dlugosci (I_, F_, S_), spacje odzielaja elementy, zamiast dlugosci w stringu sa cudzyslowy.

**Comment by nuivall** [comment]
Pisze dopiero teraz, bo mialem dzis problem z brakiem pradu.

**Comment by MGJanicki** [comment]
Nie chcę się przerzucać pomysłami i spamować wszystkim poczty, ale są 2 sprawy:
1. Jednoznakowy identyfikator jest bardzo dobrym pomysłem, dzięki za sugestię.
2. Widzę, że po prostu chcesz zrobić z tego całkowicie tekstowy format przesyłania danych. Wydaje mi się, że w ten sposób tracimy ważną zaletę memcpy - int i float mają stały rozmiar, co powinno nam oszczędzić miejsce zwłaszcza w przypadku floatów.

Zrobię tak jak ustalimy wszyscy, po prostu czekam aż Sven się wypowie na ten temat, ok?

**Comment by nuivall** [comment]
Aktualnie robie deserializacje zapytania, wiec deserializacja krotki bedzie mogla wykorzystac czesc kodu (np. ogolny pomysl).

Zasadniczo ja stawialbym na czytelnosc kodu w opzycji do szybkosci dzialania. Ja serializacje wogole rozumiem jako zamiane na string, bo tak to po prostu jakies konwertowanie do wyslania i tyle.

Ciekawostka: zauwaz, ze jesli klient i server byly by na innych maszynach to trzeba by uwzglednic byte-order.

**Comment by nuivall** [comment]
Jesli chodzi o miejsce (rozumiem ze w kontekscie przesylania przez pipe), jakas przykladowa (taka znalazlem w tescie w necie) wydajnosc pipe jest rzedu 60 MB/s (przy zapytaniu srednio 30 znakow mamy okolo 2 mln zapytan na sekunde) i mysle ze dalsze przetwarzanie zapytania przez server bedzie mialo duzo mniejsza wydajnosc (czyli przyjmujac zerowe naklady na przesylanie teoretyczna wydajnosc wyniesie duzo mniej niz 2 mln zapytan na sekunde). Co znaczy, ze procent zasobow poniesiony na przesylanie bedzie stosunkowo niski.

Ale nawet jesli bedziemy przesylac takie opakowane raw data to szkielet w serialize() i dziedziczenie w Tuple sa dobre.
