### ISSUE TITLE
AutoTestClient - check this out!

### ISSUE THREAD

**Issue by nuivall** [mrcn4/UXP1A-Linda#21]
Jakby tak nie do konca dziala ten server.
1. Timeout dziala tylko za pierwszym razem (czeka), pozniej timeouty sa natychmiastowe
2. Zapytania nigdy nie zwracaja krotek (nie wiem jeszcze gdzie blad czy tester czy serv, ale chyba serv)

**Comment by nuivall** [comment]
INPUT  INT == \* STR <= AB  ... I TIMEOUT
OUTPUT INT 1 STR "sM"  ... OK
OUTPUT INT 3 INT 6  ... OK
OUTPUT INT 2 STR "e2"  ... OK
INPUT  INT == 2 STR == \*  ... I TIMEOUT

Wiec blad jest na pewno gdzies (patrz ostatniia i przedostatnia linia)

**Comment by nuivall** [comment]
Najprawdopodobniej blad jest z tym timeout (natychmiastowy timeout)

**Comment by nuivall** [comment]
timeout naprawiony, z tym ze nadal nie input nie dziala (ale chociaz czeka)

**Comment by nuivall** [comment]
OUTPUT INT 4 STR "14"  ... Server select finish

  Server: received output message
    m_Msg.tag: 0
    m_Msg.length: 16
    Read returned: 16 bytes. Data is: INT 4 STR "14" 
output ok
OK
No Tuple input request maches output tuple, put it to db.
OUTPUT INT 6 INT 6  ... Server select finish

  Server: received output message
    m_Msg.tag: 1
    m_Msg.length: 13
    Read returned: 13 bytes. Data is: INT 6 INT 6 
No Tuple input request maches output tuple, put it to db.
output ok
OK
OUTPUT INT 2 STR "ra"  ... Server select finish

  Server: received output message
    m_Msg.tag: 2
    m_Msg.length: 16
    Read returned: 16 bytes. Data is: INT 2 STR "ra" 
No Tuple input request maches output tuple, put it to db.
output ok
OK
OUTPUT INT 2 INT 2  ... Server select finish

  Server: received output message
    m_Msg.tag: 3
    m_Msg.length: 13
    Read returned: 13 bytes. Data is: INT 2 INT 2 
No Tuple input request maches output tuple, put it to db.
output ok
OK
OUTPUT INT 9 INT 9  ... Server select finish

  Server: received output message
    m_Msg.tag: 4
    m_Msg.length: 13
    Read returned: 13 bytes. Data is: INT 9 INT 9 
No Tuple input request maches output tuple, put it to db.
output ok
OK
OUTPUT INT 1 STR "YA"  ... Server select finish

  Server: received output message
    m_Msg.tag: 5
    m_Msg.length: 16
    Read returned: 16 bytes. Data is: INT 1 STR "YA" 
No Tuple input request maches output tuple, put it to db.
output ok
OK
OUTPUT INT 5 STR "sQ"  ... Server select finish

  Server: received output message
    m_Msg.tag: 6
    m_Msg.length: 16
    Read returned: 16 bytes. Data is: INT 5 STR "sQ" 
No Tuple input request maches output tuple, put it to db.
output ok
OK
OUTPUT INT 2 INT 8  ... Server select finish

  Server: received output message
    m_Msg.tag: 7
    m_Msg.length: 13
    Read returned: 13 bytes. Data is: INT 2 INT 8 
No Tuple input request maches output tuple, put it to db.
output ok
OK
OUTPUT INT 3 STR "35"  ... Server select finish

  Server: received output message
    m_Msg.tag: 8
    m_Msg.length: 16
    Read returned: 16 bytes. Data is: INT 3 STR "35" 
No Tuple input request maches output tuple, put it to db.
output ok
OK
OUTPUT INT 2 STR "9b"  ... Server select finish

  Server: received output message
    m_Msg.tag: 9
    m_Msg.length: 16
    Read returned: 16 bytes. Data is: INT 2 STR "9b" 
No Tuple input request maches output tuple, put it to db.
output ok
OK
INPUT  INT == \* STR == \* ... Server select finish

  Server: received data access message
    m_Msg.tag: 10
    m_Msg.length: 18
    Read returned: 18 bytes. Data is: INT == \* STR == *
doInputRead
can't be sat now
TIMEOUT
I TIMEOUT
Server select finish

  Server: received cancel message
    m_Msg.tag: 11
    m_Msg.length: 0
Client request cancelled by client.
OUTPUT INT 1 STR "r2"  ... Server select finish

  Server: received output message
    m_Msg.tag: 11
    m_Msg.length: 16
    Read returned: 16 bytes. Data is: INT 1 STR "r2" 
No Tuple input request maches output tuple, put it to db.
output ok
OK
OUTPUT INT 7 INT 9  ... Server select finish

  Server: received output message
    m_Msg.tag: 12
    m_Msg.length: 13
    Read returned: 13 bytes. Data is: INT 7 INT 9 
No Tuple input request maches output tuple, put it to db.
output ok
OK
OUTPUT INT 5 STR "t0"  ... Server select finish

  Server: received output message
    m_Msg.tag: 13
    m_Msg.length: 16
    Read returned: 16 bytes. Data is: INT 5 STR "t0" 
No Tuple input request maches output tuple, put it to db.
output ok
OK
OUTPUT INT 4 STR "3x"  ... Server select finish

  Server: received output message
    m_Msg.tag: 14
    m_Msg.length: 16
    Read returned: 16 bytes. Data is: INT 4 STR "3x" 
No Tuple input request maches output tuple, put it to db.
output ok
OK
OUTPUT INT 5 INT 4  ... Server select finish

  Server: received output message
    m_Msg.tag: 15
    m_Msg.length: 13
    Read returned: 13 bytes. Data is: INT 5 INT 4 
No Tuple input request maches output tuple, put it to db.
output ok
OK
OUTPUT INT 1 STR "vw"  ... Server select finish

  Server: received output message
    m_Msg.tag: 16
    m_Msg.length: 16
    Read returned: 16 bytes. Data is: INT 1 STR "vw" 
No Tuple input request maches output tuple, put it to db.
output ok
OK
OUTPUT INT 6 INT 9  ... Server select finish

  Server: received output message
    m_Msg.tag: 17
    m_Msg.length: 13
    Read returned: 13 bytes. Data is: INT 6 INT 9 
No Tuple input request maches output tuple, put it to db.
output ok
OK
OUTPUT INT 3 STR "Ga"  ... Server select finish

  Server: received output message
    m_Msg.tag: 18
    m_Msg.length: 16
    Read returned: 16 bytes. Data is: INT 3 STR "Ga" 
No Tuple input request maches output tuple, put it to db.
output ok
OK
OUTPUT INT 9 INT 10  ... Server select finish

  Server: received output message
    m_Msg.tag: 19
    m_Msg.length: 14
    Read returned: 14 bytes. Data is: INT 9 INT 10 
No Tuple input request maches output tuple, put it to db.
output ok
OK
OUTPUT INT 5 STR "U3"  ... Server select finish

  Server: received output message
    m_Msg.tag: 20
    m_Msg.length: 16
    Read returned: 16 bytes. Data is: INT 5 STR "U3" 
No Tuple input request maches output tuple, put it to db.
output ok
OK
INPUT  INT == \* INT == \* ... Server select finish

  Server: received data access message
    m_Msg.tag: 21
    m_Msg.length: 18
    Read returned: 18 bytes. Data is: INT == \* INT == *
doInputRead
can't be sat now
^C

**Comment by nuivall** [comment]
naprawione, zostaje przetestowac kilku autotestclient na raz

**Comment by nuivall** [comment]
2 clienty sie zakleszczaja !!!

**Comment by mrcn4** [comment]
W jakiej sytuacji, jaka komenda? Serwer jest jednowątkowy więc ciężko go zakleszczyć, jakiś semafor może leży?

**Comment by nuivall** [comment]
makefile_autotests

**Comment by nuivall** [comment]
./server ../autoclient ../autoclient

**Comment by mrcn4** [comment]
Ok, zakleszczenie zauważyłem, pozostaje sprawdzić gdzie występuje.
Raz udało mi się złapać przy cancelRequest, nie wypisał komunikatu potwierdzającego znalezienie requestu w kolejce.

**Comment by nuivall** [comment]
tu fragment z zakleszczeniem:

OUTPUT INT 1 STR "Ne"  ... OUTPUT INT 1 STR "Ne"  ... OK
OK
OUTPUT INT 2 INT 5  ... OUTPUT INT 2 INT 5  ... OK
OK
OUTPUT INT 0 INT 4  ... OUTPUT INT 0 INT 4  ... OK
OK
OUTPUT INT 2 STR "e9"  ... OUTPUT INT 2 STR "e9"  ... OK
OK
INPUT  INT <= 2 STR >= dF  ... INPUT  INT <= 2 STR >= dF  ... I 
RECIVD INT 0 STR "m7" 
I 
RECIVD INT 0 STR "m7" 
INPUT  INT == 2 STR == QS  ... INPUT  INT == 2 STR == QS  ... I TIMEOUT
I TIMEOUT
OUTPUT INT 3 STR "UA"  ... OUTPUT INT 3 STR "UA"  ... ^C

**Comment by nuivall** [comment]
jak widac 2 klient na raz robia:
OUTPUT INT 3 STR "UA" ...
OUTPUT INT 3 STR "UA" ...

**Comment by nuivall** [comment]
*2 klienty

**Comment by mrcn4** [comment]
Złapałem na bardzo szybkim zakleszczeniu: 
List of procs to run:
./client
./client
List of args to run:
./client
./client
20053: INPUT  INT >= 2 INT >= 3  ... 20052: INPUT  INT >= 2 INT >= 3  ... Server select finish

  Server: received data access message
    m_Msg.tag: 0
    m_Msg.length: 19
doInputRead
can't be sat now

  Server: received data access message
    m_Msg.tag: 0
    m_Msg.length: 19
doInputRead
can't be sat now
TIMEOUT
R TIMEOUT
Server select finish

  Server: received cancel message
20053: OUTPUT INT 2 INT 9  ...     m_Msg.tag: 1
    m_Msg.length: 0
TIMEOUT
R TIMEOUT
20052: OUTPUT INT 2 INT 9  ...

**Comment by nuivall** [comment]
problem jest tez taki ze mam w autoclient srand(time(NULL)) i w efekcie seed na obu autoclient jest identyczny

**Comment by nuivall** [comment]
ale gdy to zmienilem to widze ze ewidentnie ze jednoczesny OUTPUT identycznych krotek zakleszcza!

**Comment by nuivall** [comment]
nie da rady odpalic tego w graficznym debugerze i zobaczyc gdzie sie zatrzymuje serv? Bo ja niestety pod windowsem mam eclipse.

**Comment by mrcn4** [comment]
jak to uruchamiasz? na maszynie wirutalnej? Też nie pracuję w graficznym interfejsie, sprawdzę zaraz pod gdb może

**Comment by nuivall** [comment]
pod virtualbox ubuntu (katalog wspoldzielony).

Problem jest ewidentnie wtedy gdy przychodzi od dwoch klientow identyczna
operacja wstawienia do bazy (te same dane)

**Comment by mrcn4** [comment]
nie zwiększany iterator w pętli, zaraz sprawdzę czy teraz działa.

**Comment by mrcn4** [comment]
2 klientów 6 razy po ~300 zapytań bez zakleszczeń serwera. 5 klientów bez zakleszczeń serwera. Zdaje się działać. Wcześniej działało tylko fartem.

**Comment by nuivall** [comment]
uff

**Comment by nuivall** [comment]
a odpal 2 razy binary autoclient1

**Comment by nuivall** [comment]
jestem w pociągu

**Comment by nuivall** [comment]
jak działa (2 clients robią identyczne akcje w tym samym czasie) to wyślij kod do blin, chciał chciał mieć go przed 14

**Comment by mrcn4** [comment]
commited, dwa razy autoclient (zwykły z kompilacji) działa.

**Comment by nuivall** [comment]
dobra to slij do blinowskiego, moze z doxygenem (jesli w miare dobrze cos tam generuje)

**Comment by nuivall** [comment]
marcin j mowil ze sytuacje awaryjne w dokumentacji sa do doszlifowania.

**Comment by mrcn4** [comment]
Myślę że nie tylko w dokumentacji :)
