### ISSUE TITLE
Parsowanie zapytania(wyszukiwanie, zapisywanie)

### ISSUE THREAD

**Issue by mrcn4** [mrcn4/UXP1A-Linda#4]

**Comment by mrcn4** [comment]
Zapytanie miałoby zostać sparsowane do zaproponowanej klasy (prawie identyczna jak krotka)

**Comment by MGJanicki** [comment]
Z punktu widzenia klienta tak naprawdę nie potrzebujemy żadnej klasy trzymającej zapytanie - samo polecenie jest identyfikowane poprzez id komunikatu wysyłanego przez pipe, a jeżeli chodzi o polecenie output wystarczy podać krotkę, natomiast jeżeli chodzi o input i read potrzebujemy wzorca krotki - można tam przypisać jakieś domyślne wartości (np. 0 dla int i float i "" dla stringa).

Gdybyśmy zdecydowali się na tego typu rozwiązanie to z punktu widzenia serwera potrzebne byłoby opakowanie mówiące o typie zapytania (input/output/read) i krotka której można zmieniać wartości, żeby nadpisać dane ze wzorca (wymaga to dopisania raptem 3 banalnych funkcji). Rozwiązywałoby to też problem szukania wzorca bo można by po prostu próbować wrzucać kolejne elementy do krotki i wyjątek sygnalizowałby o niepowodzeniu - przechodzimy do następnej krotki z bazy i próbujemy znowu. Co wy na to?

**Comment by nuivall** [comment]
Nie bardzo rozumiem. Sygnalizowanie sytuacji nie-awaryjnej za pomoca wyjatku to sredni pomysl. Proponuje jednak zrobic klase zapytania.

Ja sie moge tym zajac, zrobie parsowanie zapytania i wyszukiwanie. Zapisywanie bedzie trywialne jesli: baza danych to vector of Tuple

MarcinJ: popraw serializacje, a potem zrob moze interface ogolnego semafora
