### ISSUE TITLE
Standard C++

### ISSUE THREAD

**Issue by nuivall** [mrcn4/UXP1A-Linda#8]
Czy używamy C++11 ? VS 2012 wspiera częściowo (domyślnie włączone), GCC 4.8 wspiera prawie w całości (flaga -std=c++11)

**Comment by mrcn4** [comment]
do czego nam się on przyda? Myślę że jeśli nie ma potrzeby zostańmy przy poprzednim standardzie. W razie czego mamy zgodność wsteczną.

**Comment by nuivall** [comment]
Nie wiem konkretnie do czego. Dla mnie to przede wszystkim typ auto, pętla for_each/for, i inicjalizacja zwykłych zmiennych klasy jak zmiennych staycznych.

**Comment by mrcn4** [comment]
Ze względu na to że komunikację mamy mieć na potokach nienazwanych VS nie gra roli. Skoro GCC to wspiera bez problemów i może to ułatwić kodzenie, jestem za (shared pointery też się mogą przydać).

**Comment by mrcn4** [comment]
Stosujemy C++11.
